receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

exporters:
  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  logging:
    loglevel: debug
  prometheus:
    endpoint: "otelcol:9464"
  file:
    path: /mnt/test/filename.json

processors:
  batch:
  # spanmetrics:
    # metrics_exporter: prometheus

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [file, otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]